# Generated by Django 4.1 on 2022-12-29 17:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='date',
            new_name='date_end',
        ),
        migrations.AddField(
            model_name='entry',
            name='date_start',
            field=models.DateField(default=datetime.date(2022, 12, 29)),
        ),
        migrations.AddField(
            model_name='entry',
            name='day_of_week_end',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='entry',
            name='day_of_week_start',
            field=models.CharField(default='Thursday', max_length=10),
        ),
        migrations.AddField(
            model_name='entry',
            name='tags',
            field=models.TextField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='entry',
            name='text',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='entry',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
