# Generated by Django 4.1 on 2022-12-29 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0004_alter_entry_date_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='date_end',
            field=models.DateField(null=True),
        ),
    ]
