# Generated by Django 4.1 on 2022-12-29 17:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0005_alter_entry_date_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='date_end',
            field=models.DateField(default=datetime.date(2022, 12, 29)),
        ),
    ]
