# Generated by Django 3.2.16 on 2023-01-04 02:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0006_alter_entry_date_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='date_end',
            field=models.DateField(default=datetime.date(2023, 1, 3)),
        ),
        migrations.AlterField(
            model_name='entry',
            name='date_start',
            field=models.DateField(default=datetime.date(2023, 1, 3)),
        ),
        migrations.AlterField(
            model_name='entry',
            name='day_of_week_start',
            field=models.CharField(default='Tuesday', max_length=10),
        ),
        migrations.AlterField(
            model_name='entry',
            name='text',
            field=models.TextField(max_length=5000),
        ),
    ]
